[package]
authors = ["Joe Ranweiler <joe@lemma.co>"]
name = "stamp"
license-file = "LICENSE"
readme = "README.md"
version = "0.1.0"

[dependencies]
unicode-segmentation = "1.2.0"
unicode-width = "0.1.4"